### ISSUE TITLE
Module detection.

### ISSUE THREAD

**Issue by Daerckdev** [symbuzzer/systemless-hosts-KernelSU-module#11]
After installing the latest version of the module, NativeDetector by reveny and MemoryDetector could found the mount point in /system/etc.
I've tested it with ZygiskNext 133 and 141, both with and without shamiko.

**Comment by symbuzzer** [comment]
So what is the problem?

**Comment by Daerckdev** [comment]
The way the module works could be used by some applications (e.g. banking apps) to detect root, and apparently shamiko isn't able to hide it.
If it's not fixable or you're not interested in it, I suggest at least adding some clarification in the README

**Comment by symbuzzer** [comment]
I understand now, thank you for your feedback. If there is a workaround you can suggest, I can try it @Daerckdev

**Comment by Daerckdev** [comment]
Not at the moment as I don't know how this detection works, I think it's something to do with the manual mount in the script, so maybe shamiko can't detect it (you can see the mount point with cat /proc/mounts). I'll have a look at it in the next few days.

**Comment by symbuzzer** [comment]
@Lu5ck which specific apps for example? only AdAway?

**Comment by symbuzzer** [comment]
Actually, the most possible solution is for Adaway to directly change the hosts file in the module.

**Comment by Daerckdev** [comment]
@Lu5ck The problem is that the hosts file is constantly being read by some system processes to resolve IPs. I don't think dynamic mounting would work.

**Comment by Daerckdev** [comment]
> doesn't work, can see ksu mounted on system/etc

what apps can see it?

**Comment by symbuzzer** [comment]
> > Can anyone test and send feedbacks new beta which builded with @Daerckdev 's [PR](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/pull/13)?
> > [systemless-hosts-KernelSU-module-beta.zip](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/files/13674835/systemless-hosts-KernelSU-module-beta.zip)
> 
> doesn't work, can see ksu mounted on system/etc
> 
> > @Lu5ck The problem is that the hosts file is constantly being read by some system processes to resolve IPs. I don't think dynamic mounting would work.
> 
> 🤔🤔 I see HuskyDG created a dynamc mount for Revanced Youtube. From my limited guessing of what it does, it mount when system (UID below 10000) called, when youtube called, when system ui called which means all other user apps cannot see the mount.
> 
> So what if we unmount it when specific sensitive apps calls and then mount for others? I don't know programming so I can't put this theory to test.

It looks good in theory. But etc/hosts is not only called by AdAway. I'm sure there are dozens of service threads on the Unix system that call this, but I can't prove it.

**Comment by LordMagnos1** [comment]
[[Systemless Hosts](https://github.com/dchristl/KernelSU-systemless-hosts/releases)](url)
I found this version of Systemless Hosts that made it work without any errors 💯.NFC: now working (previously didn't work at all with the Systemless Hosts module activated).SafetyNet: Everything successful.Play Store: certified (Netflix now appears to install).Banks: working.Adaway: working, blocking ads.
My modules:Play Integrity Next v14.1Systemless Hosts for KernelSU v1.0Zygisk-LSposed v1.9.2Shamiko v0.7.5Zygisk Next v4-0.8.1

**Comment by xberzerker** [comment]
i can confirm same problem here.
as well as that https://github.com/dchristl/KernelSU-systemless-hosts/releases
solves
