### ISSUE TITLE
Compatibility Issue on Pixel 8 Pro with LSposed

### ISSUE THREAD

**Issue by leon0207** [symbuzzer/systemless-hosts-KernelSU-module#14]
Hi, Hope you're doing well! 👋 I've been using your module on my Pixel 8 Pro, and it's been awesome! However, I've run into a little hiccup. It seems like LSposed doesn't play nice when your module is in the mix. I've got a hunch that it might be due to a compatibility issue with 32-bit systems. Any chance you could roll out a version that exclusively supports 64-bit? That would be a game-changer! thanks, and keep up the fantastic work!

**Comment by symbuzzer** [comment]
That's all I can do
