### ISSUE TITLE
install newest zip can't enter system

### ISSUE THREAD

**Issue by wentywenty** [symbuzzer/systemless-hosts-KernelSU-module#15]
redmi note 12 turbo 
miui14.0.23
android13
kernelsu 0.7.2
kernel version 5.10.149-android12-9
zygisk next v4-0.9.0
shamiko v1.0
systemless-hosts-KernelSU-module v1.1.2

After flashing the module and restarting, the phone is stuck on the startup screen and cannot enter the system.

How do I grab the logs

thankyou.

**Comment by symbuzzer** [comment]
@wentywenty how was this problem fixed?

**Comment by wentywenty** [comment]
Just disable this module🙏
