### ISSUE TITLE
using this module trigger root detection in Banking App

### ISSUE THREAD

**Issue by collisee** [symbuzzer/systemless-hosts-KernelSU-module#3]
Like the title said, the module trigger root detection in banking app somehow, specifically Vietcombank.

I'm using the lastest KernelSU + systemless host
![Screenshot_20230721-160909_VCB Digibank~2](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/136151261/4ee56288-10db-4678-8b5d-f3ffdda73a9c)

The text in the screenshot translate to: "Applications running on Root devices may pose a security risk.  Please check the device again."

**Comment by ashoktvm** [comment]
I am also facing the same issue. App I use is YONO SBI

**Comment by symbuzzer** [comment]
@ashoktvm @collisee Can u try to uninstall manager temp. and try again?

**Comment by collisee** [comment]
> @ashoktvm @collisee Can u try to uninstall manager temp. and try again?

nope, it didn't work

**Comment by symbuzzer** [comment]
@collisee So uninstalling this module fixes problem? I want to be sure it caused from module or not

**Comment by collisee** [comment]
> @collisee So uninstalling this module fixes problem? I want to be sure it caused from module or not

yes, it did solve the problem

**Comment by symbuzzer** [comment]
Please use displax's safetynet fix mod for now: https://github.com/Displax/safetynet-fix/releases/tag/v2.4.0-MOD_2.0

@HuskyDG

**Comment by collisee** [comment]
> Please use displax's safetynet fix mod for now: https://github.com/Displax/safetynet-fix/releases/tag/v2.4.0-MOD_2.0
> 
> @HuskyDG

It still didn't solve the issue.

![Screenshot_20230722-103017_KernelSU](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/136151261/20e58fa8-65fd-42d7-8a89-554e6c4f8fa2)
![Screenshot_20230722-103115_VCB Digibank](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/136151261/62c97729-60dc-4eed-bead-3543288bd3e8)

**Comment by collisee** [comment]
> Please use displax's safetynet fix mod for now: https://github.com/Displax/safetynet-fix/releases/tag/v2.4.0-MOD_2.0
> 
> @HuskyDG
Using HuskyDG's overlay unmount module worked, but may cause bootloop when using font changer module (Ex: Oh My Font)

https://github.com/HuskyDG/ksu_unmount_injector

**Comment by collisee** [comment]
> Please use displax's safetynet fix mod for now: https://github.com/Displax/safetynet-fix/releases/tag/v2.4.0-MOD_2.0
> 
> @HuskyDG

Using HuskyDG's Overlay Unmount worked for me, it may cause bootloop when using Font Changer module (Ex: Oh My Font)
https://github.com/HuskyDG/ksu_unmount_injector

**Comment by symbuzzer** [comment]
I will compare both modules and try to fix, thanks

**Comment by collisee** [comment]
> I will compare both modules and try to fix, thanks

shall I close this issue now?

**Comment by symbuzzer** [comment]
No. Can you check something for me?
Remove font plugin and install HuskuDG's hosts module. Check if safetynet status changed

**Comment by collisee** [comment]
> No. Can you check something for me? Remove font plugin and install HuskuDG's hosts module. Check if safetynet status changed

idk what do you mean by HuskyDG's hosts module. Installing this module did not change SafetyNet status

**Comment by symbuzzer** [comment]
Meant https://github.com/HuskyDG/ksu_unmount_injector

**Comment by collisee** [comment]
I already removed the font module, the font used in the screenshot is provided by the rom
and yes, remove font module and install HuskyDG's module didn't change the SafetyNet status

**Comment by symbuzzer** [comment]
Okey thanks, will try to fix with his codes without unmount feature

**Comment by ashoktvm** [comment]
> @collisee So uninstalling this module fixes problem? I want to be sure it caused from module or not

No need to uninstall it. just disabling it makes banking apps work

**Comment by ashoktvm** [comment]
> > Please use displax's safetynet fix mod for now: https://github.com/Displax/safetynet-fix/releases/tag/v2.4.0-MOD_2.0
> > @HuskyDG
> 
> Using HuskyDG's Overlay Unmount worked for me, it may cause bootloop when using Font Changer module (Ex: Oh My Font) https://github.com/HuskyDG/ksu_unmount_injector

It broke another model Myui5 dialer for me

**Comment by collisee** [comment]
try disable umount module in MyUI5 Dialer profile?
![Screenshot_20230722-152734_KernelSU](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/136151261/151d6365-37a0-42e3-8b16-77dcaf1d1fe2)

**Comment by ashoktvm** [comment]
> try disable umount module in MyUI5 Dialer profile?
> ![Screenshot_20230722-152734_KernelSU](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/136151261/151d6365-37a0-42e3-8b16-77dcaf1d1fe2)
> 

It doesn't show in apps section to do that

**Comment by collisee** [comment]
did you enable show system app
![Uploading Screenshot_20230722-160058_KernelSU.png…]()

**Comment by ashoktvm** [comment]
> did you enable show system app
> ![Screenshot_20230722-160058_KernelSU](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/136151261/d9cc678c-2594-4673-a530-a4227c43f1af)
> 
> 

Just tried in the module u mentioned again and now the dialer doesn't even show in apps section

**Comment by collisee** [comment]
I don't use MyUI Dialer so I can't help you with this. Wait for the fix I guess

**Comment by collisee** [comment]
> Edit: Sorry it shows in system apps and that option is disabled to select or deselect
choose "custom" first and you can disable the option

**Comment by ashoktvm** [comment]
> I don't use MyUI Dialer so I can't help you with this. Wait for the fix I guess

I had to disable the kernelsu unmount module, Rebooted and disabled unmount modules and then enable kernel su unmount module and now it worked. Thanks for the help

**Comment by ashoktvm** [comment]
But the dialer app keeps closing. So looks like I have to wait for the fix

**Comment by symbuzzer** [comment]
@ashoktvm @collisee  can you check this test release?
https://github.com/symbuzzer/systemless-hosts-KernelSU-module/releases/download/v1.1.0/systemless-hosts-KernelSU-module.zip

**Comment by collisee** [comment]
it worked perfectly for me, tysm for your work man

**Comment by symbuzzer** [comment]
all credits go to @HuskyDG, closing...

**Comment by symbuzzer** [comment]
@collisee please uninstall test version and install latest again

**Comment by symbuzzer** [comment]
You gave me wrong feedback. v1.1.0 breaks safetynet :( Re-opening the issue...

**Comment by collisee** [comment]
I didn't know man, I was using SafetyNet Universal fix

**Comment by ashoktvm** [comment]
> You gave me wrong feedback. v1.1.0 breaks safetynet :( Re-opening the issue...

Yeah was just about to post that

**Comment by ashoktvm** [comment]
> I didn't know man, I was using SafetyNet Universal fix

Even using that didn't help with safetynet

**Comment by collisee** [comment]
![Screenshot_20230723-000012_Yet Another SafetyNet Attestation Checker](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/136151261/9c15e4ec-cec7-4b06-9d0a-7a0ec6a172e1)

**Comment by ashoktvm** [comment]
![Uploading Screenshot_20230722-223138_KernelSU.png…]()

**Comment by ashoktvm** [comment]
![Uploading Screenshot_20230722-223206_Yet Another SafetyNet Attestation Checker.png…]()

**Comment by ashoktvm** [comment]
![IMG_20230722_223512_248.jpg](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/45116583/678d38ac-bda8-468e-9b4c-1f9f2bec9ad2)

![IMG_20230722_223512_923.jpg](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/45116583/d88ddc5d-68af-4fa3-8dc9-50e99426e53f)

**Comment by symbuzzer** [comment]
@collisee please uninstall universal safetynet fixer before reporting.
@ashoktvm I see, please update v1.1.1 and wait for fix.

**Comment by collisee** [comment]
idk man, it worked on my device, that's why I said It worked perfectly. Weird
![Screenshot_20230723-000744_Yet Another SafetyNet Attestation Checker](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/136151261/9d48c331-f27b-441e-8342-d39ee1565eae)
![Screenshot_20230723-000737_KernelSU](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/136151261/d9f9c6f4-5082-4cdc-97d1-18f918a5ee81)

**Comment by collisee** [comment]
> @collisee please uninstall universal safetynet fixer before reporting. @ashoktvm I see, please update v1.1.1 and wait for fix.
sorry for the confusion

**Comment by symbuzzer** [comment]
can u send me apks or apk download links (not google play link) of triggered apk's please for testing? @ashoktvm @collisee

**Comment by collisee** [comment]
https://mega.nz/file/1ck2wLiT#uX6J9zD3FN5ujsksLU_A6asp1AvN0aus9tSf2QqfBJk

**Comment by ashoktvm** [comment]
> can u send me apks or apk download links (not google play link) of triggered apk's please for testing? @ashoktvm @collisee 

https://yono-sbi-the-mobile-banking-and-lifestyle-app.en.softonic.com/android

**Comment by symbuzzer** [comment]
> > can u send me apks or apk download links (not google play link) of triggered apk's please for testing? @ashoktvm @collisee
> 
> https://yono-sbi-the-mobile-banking-and-lifestyle-app.en.softonic.com/android

it is redirecting to google play store

**Comment by ashoktvm** [comment]
> > > can u send me apks or apk download links (not google play link) of triggered apk's please for testing? @ashoktvm @collisee
> > 
> > https://yono-sbi-the-mobile-banking-and-lifestyle-app.en.softonic.com/android
> 
> it is redirecting to google play store

https://m.apktoy.com/download/com.sbi.lotusintouch_1.23.47_free.html

**Comment by symbuzzer** [comment]
These applications detect the changes made by overlyfs. So, we should continue the road with horses. I started to prepare another module, one that works with a completely different method. It will probably be named "AdAway KernelSU Helper". Want to test it when it's ready?

**Comment by ashoktvm** [comment]
> These applications detect the changes made by overlyfs. So, we should continue the road with horses. I started to prepare another module, one that works with a completely different method. It will probably be named "AdAway KernelSU Helper". Want to test it when it's ready?

Sure. But adaway hosts not getting enabled after installing 1.1.1

**Comment by symbuzzer** [comment]
> > These applications detect the changes made by overlyfs. So, we should continue the road with horses. I started to prepare another module, one that works with a completely different method. It will probably be named "AdAway KernelSU Helper". Want to test it when it's ready?
> 
> Sure. But adaway hosts not getting enabled after installing 1.1.1

Uninstall and install again please. Waiting your report sir...

**Comment by ashoktvm** [comment]
> > > These applications detect the changes made by overlyfs. So, we should continue the road with horses. I started to prepare another module, one that works with a completely different method. It will probably be named "AdAway KernelSU Helper". Want to test it when it's ready?
> > 
> > Sure. But adaway hosts not getting enabled after installing 1.1.1
> 
> Uninstall and install again please. Waiting your report sir...

Uninstall adaway or module?

**Comment by symbuzzer** [comment]
> > > > These applications detect the changes made by overlyfs. So, we should continue the road with horses. I started to prepare another module, one that works with a completely different method. It will probably be named "AdAway KernelSU Helper". Want to test it when it's ready?
> > > 
> > > 
> > > Sure. But adaway hosts not getting enabled after installing 1.1.1
> > 
> > 
> > Uninstall and install again please. Waiting your report sir...
> 
> Uninstall adaway or module?

module. uninstall, reboot, install

**Comment by ashoktvm** [comment]
Uninstalled adaway and reinstalled didn't help
Uninstalled 1.1.1 and reinstalled 1.1.1 helped

**Comment by symbuzzer** [comment]
@ashoktvm @collisee Please use dirty-fix for now: https://github.com/symbuzzer/adaway-kernelsu-helper

**Comment by ashoktvm** [comment]
> @ashoktvm @collisee Please use dirty-fix for now: https://github.com/symbuzzer/adaway-kernelsu-helper

Phone is boot looping. I am using nameless rom

**Comment by symbuzzer** [comment]
> > @ashoktvm @collisee Please use dirty-fix for now: https://github.com/symbuzzer/adaway-kernelsu-helper
> 
> Phone is boot looping. I am using nameless rom

Delete ```data/adb/modules/adaway-kernelsu-helper``` folder from TWRP's file managere

**Comment by ashoktvm** [comment]
> > > @ashoktvm @collisee Please use dirty-fix for now: https://github.com/symbuzzer/adaway-kernelsu-helper
> > 
> > Phone is boot looping. I am using nameless rom
> 
> Delete ```data/adb/modules/adaway-kernelsu-helper``` folder from TWRP's file managere

Using orangefox and there is nothing modules folder

**Comment by ashoktvm** [comment]
![IMG_20230723_013735.jpg](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/45116583/2e1a9ca4-7fe2-4818-994c-967a61c58885)

**Comment by ashoktvm** [comment]
Please help

**Comment by symbuzzer** [comment]
Show me data/adb folder

**Comment by ashoktvm** [comment]
> Show me data/adb folder

![IMG_20230723_014922.jpg](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/45116583/ca2aa80d-aca7-420b-be3e-6a2be7270be7)

**Comment by symbuzzer** [comment]
Modules_update

**Comment by ashoktvm** [comment]
> Modules_update

Nothing in the as well

**Comment by symbuzzer** [comment]
try these: https://kernelsu.org/guide/rescue-from-bootloop.html

**Comment by symbuzzer** [comment]
The built-in Safe Mode of KernelSU; the operation method is to press the volume down key continuously for more than three times after the first boot screen. Note that it is press-release, press-release, press-release, not press and hold.

**Comment by ashoktvm** [comment]
Nothing is helping. Tried all the methods

**Comment by ashoktvm** [comment]
> The built-in Safe Mode of KernelSU; the operation method is to press the volume down key continuously for more than three times after the first boot screen. Note that it is press-release, press-release, press-release, not press and hold.

Nothing happens. Going to boot loop

**Comment by symbuzzer** [comment]
flash non-kernelsu supoorted kernel and try to boot

**Comment by ashoktvm** [comment]
> flash non-kernelsu supoorted kernel and try to boot

After that. Have to format the whole rom again and reinstall?

**Comment by symbuzzer** [comment]
reflash ksu kernel and check. if not work, delete data/adb folder. if still bootlooped, try to format data

**Comment by ashoktvm** [comment]
> reflash ksu kernel and check. if not work, delete data/adb folder. if still bootlooped, try to format data

What are u saying man. No backup. All my data will be gone.

**Comment by symbuzzer** [comment]
so flash non-kernelsu kernel adn backup your data first

**Comment by ashoktvm** [comment]
> reflash ksu kernel and check. if not work, delete data/adb folder. if still bootlooped, try to format data

Reflashed ksu kernel: bootloop
Deleted adb folder: worked

**Comment by ashoktvm** [comment]
> so flash non-kernelsu kernel adn backup your data first

Please delete the link. So that the other person doesn't accidentally flash and happens like me
