### ISSUE TITLE
Youtube history not get save after using this module

### ISSUE THREAD

**Issue by spidy2356** [symbuzzer/systemless-hosts-KernelSU-module#6]
Yt history not get saved which are watched on app after using this module.

**Comment by symbuzzer** [comment]
@spidy2356 I don't think it has anything to do with it. Does it continue to work after removing the module? Have you or can you check this?

**Comment by spidy2356** [comment]
@symbuzzer yes history start syncing after remove the module..I first disable the module but didn't work then remove the module and start working again

**Comment by symbuzzer** [comment]
> @symbuzzer yes history start syncing after remove the module..I first disable the module but didn't work then remove the module and start working again

Finally; are you using a modded YouTube app?

**Comment by spidy2356** [comment]
@symbuzzer yes revanced extended

**Comment by symbuzzer** [comment]
@spidy2356 Then I turn it off since the problem is not caused by the mpdule. Thank you very much for your feedback.

**Comment by spidy2356** [comment]
@symbuzzer this problem is not due to module???......but got solved after removing the module....why???...plz explain sir

**Comment by symbuzzer** [comment]
> @symbuzzer this problem is not due to module???......but got solved after removing the module....why???...plz explain sir

The filter you are using is probably blocking the s.youtube.com dns address. When I deactivate the module, this blockage disappears and the problem is solved.
